# Generated by Django 5.2.5 on 2026-04-09 21:51

import django.db.models.deletion
from django.db import migrations, models


def _single_org_id(Organization):
    org_ids = list(Organization.objects.values_list('id', flat=True)[:2])
    return org_ids[0] if len(org_ids) == 1 else None


def _membership_org_id(OrganizationMembership, user_id):
    if not user_id:
        return None
    membership = (
        OrganizationMembership.objects
        .filter(user_id=user_id, is_active=True, organization__is_active=True)
        .order_by('id')
        .first()
    )
    return membership.organization_id if membership else None


def backfill_organization_fields(apps, schema_editor):
    Organization = apps.get_model('contracts', 'Organization')
    OrganizationMembership = apps.get_model('contracts', 'OrganizationMembership')
    Workflow = apps.get_model('contracts', 'Workflow')
    Counterparty = apps.get_model('contracts', 'Counterparty')
    ClauseCategory = apps.get_model('contracts', 'ClauseCategory')
    ClauseTemplate = apps.get_model('contracts', 'ClauseTemplate')
    EthicalWall = apps.get_model('contracts', 'EthicalWall')
    SignatureRequest = apps.get_model('contracts', 'SignatureRequest')
    DataInventoryRecord = apps.get_model('contracts', 'DataInventoryRecord')
    DSARRequest = apps.get_model('contracts', 'DSARRequest')
    Subprocessor = apps.get_model('contracts', 'Subprocessor')
    TransferRecord = apps.get_model('contracts', 'TransferRecord')
    RetentionPolicy = apps.get_model('contracts', 'RetentionPolicy')
    LegalHold = apps.get_model('contracts', 'LegalHold')
    ApprovalRule = apps.get_model('contracts', 'ApprovalRule')
    ApprovalRequest = apps.get_model('contracts', 'ApprovalRequest')

    single_org_id = _single_org_id(Organization)

    for workflow in Workflow.objects.filter(organization__isnull=True).select_related('contract'):
        workflow.organization_id = (
            getattr(workflow.contract, 'organization_id', None)
            or _membership_org_id(OrganizationMembership, workflow.created_by_id)
            or single_org_id
        )
        workflow.save(update_fields=['organization'])

    for template in ClauseTemplate.objects.filter(organization__isnull=True).select_related('category'):
        template.organization_id = (
            getattr(template.category, 'organization_id', None)
            or _membership_org_id(OrganizationMembership, template.created_by_id)
            or single_org_id
        )
        template.save(update_fields=['organization'])

    for category in ClauseCategory.objects.filter(organization__isnull=True):
        clause_org_ids = list(
            ClauseTemplate.objects.filter(category_id=category.id, organization__isnull=False)
            .values_list('organization_id', flat=True)
            .distinct()[:2]
        )
        category.organization_id = clause_org_ids[0] if len(clause_org_ids) == 1 else single_org_id
        category.save(update_fields=['organization'])

    for signature in SignatureRequest.objects.filter(organization__isnull=True).select_related('contract', 'document'):
        signature.organization_id = (
            signature.contract.organization_id
            or getattr(signature.document, 'organization_id', None)
            or _membership_org_id(OrganizationMembership, signature.created_by_id)
            or single_org_id
        )
        signature.save(update_fields=['organization'])

    for record in DataInventoryRecord.objects.filter(organization__isnull=True).select_related('client'):
        record.organization_id = (
            getattr(record.client, 'organization_id', None)
            or _membership_org_id(OrganizationMembership, record.created_by_id)
            or single_org_id
        )
        record.save(update_fields=['organization'])

    for dsar in DSARRequest.objects.filter(organization__isnull=True).select_related('client'):
        dsar.organization_id = (
            getattr(dsar.client, 'organization_id', None)
            or _membership_org_id(OrganizationMembership, dsar.created_by_id)
            or _membership_org_id(OrganizationMembership, dsar.assigned_to_id)
            or single_org_id
        )
        dsar.save(update_fields=['organization'])

    for wall in EthicalWall.objects.filter(organization__isnull=True).select_related('matter', 'client'):
        wall.organization_id = (
            getattr(wall.matter, 'organization_id', None)
            or getattr(wall.client, 'organization_id', None)
            or _membership_org_id(OrganizationMembership, wall.created_by_id)
            or single_org_id
        )
        wall.save(update_fields=['organization'])

    for hold in LegalHold.objects.filter(organization__isnull=True).select_related('matter', 'client'):
        hold.organization_id = (
            getattr(hold.matter, 'organization_id', None)
            or getattr(hold.client, 'organization_id', None)
            or _membership_org_id(OrganizationMembership, hold.issued_by_id)
            or single_org_id
        )
        hold.save(update_fields=['organization'])

    for transfer in TransferRecord.objects.filter(organization__isnull=True).select_related('contract', 'subprocessor'):
        transfer.organization_id = (
            getattr(transfer.contract, 'organization_id', None)
            or getattr(transfer.subprocessor, 'organization_id', None)
            or _membership_org_id(OrganizationMembership, transfer.created_by_id)
            or single_org_id
        )
        transfer.save(update_fields=['organization'])

    for approval in ApprovalRequest.objects.filter(organization__isnull=True).select_related('contract', 'rule'):
        approval.organization_id = (
            getattr(approval.contract, 'organization_id', None)
            or getattr(approval.rule, 'organization_id', None)
            or _membership_org_id(OrganizationMembership, approval.assigned_to_id)
            or _membership_org_id(OrganizationMembership, approval.decided_by_id)
            or single_org_id
        )
        approval.save(update_fields=['organization'])

    for model in [Subprocessor, RetentionPolicy, ApprovalRule]:
        rows = model.objects.filter(organization__isnull=True)
        for row in rows:
            owner_user_id = getattr(row, 'created_by_id', None) or getattr(row, 'specific_approver_id', None)
            row.organization_id = _membership_org_id(OrganizationMembership, owner_user_id) or single_org_id
            row.save(update_fields=['organization'])

    for counterparty in Counterparty.objects.filter(organization__isnull=True):
        counterparty.organization_id = single_org_id
        counterparty.save(update_fields=['organization'])


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_add_org_fk_to_budget_and_due_diligence'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='contracts.organization'),
        ),
        migrations.AddField(
            model_name='approvalrule',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='contracts.organization'),
        ),
        migrations.AddField(
            model_name='clausecategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause_categories', to='contracts.organization'),
        ),
        migrations.AddField(
            model_name='clausetemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause_templates', to='contracts.organization'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='contracts.organization'),
        ),
        migrations.AddField(
            model_name='datainventoryrecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_inventory_records', to='contracts.organization'),
        ),
        migrations.AddField(
            model_name='dsarrequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dsar_requests', to='contracts.organization'),
        ),
        migrations.AddField(
            model_name='ethicalwall',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ethical_walls', to='contracts.organization'),
        ),
        migrations.AddField(
            model_name='legalhold',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_holds', to='contracts.organization'),
        ),
        migrations.AddField(
            model_name='retentionpolicy',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retention_policies', to='contracts.organization'),
        ),
        migrations.AddField(
            model_name='signaturerequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='contracts.organization'),
        ),
        migrations.AddField(
            model_name='subprocessor',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprocessors', to='contracts.organization'),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_records', to='contracts.organization'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='contracts.organization'),
        ),
        migrations.AlterField(
            model_name='clausecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(backfill_organization_fields, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='clausecategory',
            unique_together={('organization', 'name')},
        ),
    ]
