# Generated by Django 5.2.13 on 2026-04-13 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_approvalrequest_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['organization', 'status', '-updated_at'], name='ctr_org_stat_upd_ix'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['organization', 'end_date'], name='ctr_org_end_ix'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['organization', 'renewal_date'], name='ctr_org_renew_ix'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['organization', 'created_at'], name='ctr_org_created_ix'),
        ),
    ]
