# Generated by Django 5.2.13 on 2026-04-13 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contract_ctr_org_stat_upd_ix_contract_ctr_org_end_ix_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['organization', '-updated_at'], name='ctr_org_upd_ix'),
        ),
    ]
