# Generated by Django 5.2.13 on 2026-04-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contract_ctr_org_upd_ix'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='session_revocation_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
