# Generated by Django 5.2.13 on 2026-04-13 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_userprofile_session_revocation_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowtemplate',
            options={'ordering': ['name', '-version', '-created_at']},
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='contracts.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
