# Generated by Django 5.2.13 on 2026-04-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_alter_workflowtemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='require_mfa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mfa_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
