# Generated by Django 5.2.13 on 2026-04-14 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_organization_identity_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSCIMGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scim_groups', to='contracts.organization')),
            ],
            options={
                'ordering': ['organization__name', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSCIMGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='contracts.organizationscimgroup')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='contracts.organizationmembership')),
            ],
            options={
                'unique_together': {('group', 'membership')},
            },
        ),
        migrations.AddField(
            model_name='organizationscimgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='scim_group_memberships', through='contracts.OrganizationSCIMGroupMembership', to='contracts.organizationmembership'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationscimgroup',
            unique_together={('organization', 'display_name')},
        ),
    ]
