# Generated by Django 5.2.13 on 2026-04-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_add_scim_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='saml_slo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organizationscimgroup',
            name='nested_groups',
            field=models.ManyToManyField(blank=True, related_name='parent_groups', to='contracts.organizationscimgroup'),
        ),
    ]
