# Generated by Django 5.2.13 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_saml_slo_nested_scim_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='scim_external_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
