# Generated by Django 5.2.13 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_organizationmembership_scim_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mfa_enrollment_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mfa_enrollment_code_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mfa_enrollment_code_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
