# Generated by Django 5.2.13 on 2026-04-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_userprofile_mfa_enrollment_code_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
