# Generated by Django 5.2.13 on 2026-04-14 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_userprofile_mfa_recovery_code_hashes_backgroundjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='delegated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='delegated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_approval_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClausePlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fallback_position', models.TextField(blank=True)),
                ('jurisdiction_scope', models.CharField(choices=[('EU', 'European Union'), ('US', 'United States'), ('UK', 'United Kingdom'), ('GLOBAL', 'Global/Universal'), ('CUSTOM', 'Custom')], default='GLOBAL', max_length=10)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clause_playbooks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause_playbooks', to='contracts.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClauseVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction_scope', models.CharField(choices=[('EU', 'European Union'), ('US', 'United States'), ('UK', 'United Kingdom'), ('GLOBAL', 'Global/Universal'), ('CUSTOM', 'Custom')], default='GLOBAL', max_length=10)),
                ('contract_type', models.CharField(blank=True, max_length=50)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('fallback_content', models.TextField(blank=True)),
                ('playbook_notes', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause_variants', to='contracts.organization')),
                ('playbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='contracts.clauseplaybook')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='contracts.clausetemplate')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationAPIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='API token', max_length=200)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_last4', models.CharField(blank=True, max_length=4)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_tokens', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='contracts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
