# Generated by Django 5.2.13 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0022_salesforce_connection_and_field_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='source_last_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='source_system',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='contract',
            name='source_system_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='source_system_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['organization', 'source_system', 'source_system_id'], name='ctr_org_src_ref_ix'),
        ),
    ]
