# Generated by Django 5.2.13 on 2026-04-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0023_contract_source_reconciliation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_source', models.CharField(choices=[('API', 'API'), ('COMMAND', 'Command'), ('WORKER', 'Worker')], default='API', max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('dry_run', models.BooleanField(default=False)),
                ('limit_applied', models.PositiveIntegerField(default=200)),
                ('source_object', models.CharField(blank=True, max_length=80)),
                ('fetched_records', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_runs', to='contracts.salesforceorganizationconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesforce_sync_runs', to='contracts.organization')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesforce_sync_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='salesforcesyncrun',
            index=models.Index(fields=['organization', '-started_at'], name='sf_sync_org_time_ix'),
        ),
        migrations.AddIndex(
            model_name='salesforcesyncrun',
            index=models.Index(fields=['organization', 'status'], name='sf_sync_org_status_ix'),
        ),
    ]
