# Generated by Django 5.2.13 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_salesforcesyncrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundjob',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backgroundjob',
            name='dead_lettered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backgroundjob',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
