# Generated by Django 5.2.5 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0029_restore_matter_legacy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='deadline_type',
            field=models.CharField(choices=[('COURT', 'Court Deadline'), ('FILING', 'Filing Deadline'), ('SOL', 'Statute of Limitations'), ('CONTRACT', 'Contract Deadline'), ('REGULATORY', 'Regulatory Deadline'), ('INTERNAL', 'Internal Deadline'), ('CLIENT', 'Client Deadline'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
