# Generated by Django 5.2.5 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0030_restore_deadline_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='reminder_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
