# Generated by Django 5.2.5 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0031_restore_deadline_reminder_days'),
    ]

    operations = [
        # The `task_type` column was introduced earlier in 0012 and already exists
        # in the schema. This migration is kept as a dependency placeholder so the
        # later trust account migration keeps its original ordering without trying
        # to add the column again.
    ]
