# Generated by Django 5.2.5 on 2026-04-20

from django.db import migrations, models


def _ensure_matter_table(apps, schema_editor):
    """
    Repair older/shared databases where Matter table artifacts are partially
    present or missing. This recreates the main contracts_matter table only
    when it is absent, and leaves the existing M2M through table untouched.
    """
    Matter = apps.get_model('contracts', 'Matter')
    existing_tables = set(schema_editor.connection.introspection.table_names())

    if Matter._meta.db_table in existing_tables:
        return

    attrs = {
        '__module__': __name__,
        'Meta': type(
            'Meta',
            (),
            {
                'app_label': 'contracts',
                'db_table': Matter._meta.db_table,
                'managed': False,
            },
        ),
    }
    for field in Matter._meta.local_fields:
        attrs[field.name] = field.clone()

    MatterRepair = type('MatterRepair', (models.Model,), attrs)
    schema_editor.create_model(MatterRepair)

    through_model = Matter.team_members.through
    if through_model._meta.db_table not in existing_tables:
        schema_editor.create_model(through_model)


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0031_restore_deadline_reminder_days'),
    ]

    operations = [
        migrations.RunPython(
            code=_ensure_matter_table,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
