# Generated by Django 5.2.5 on 2026-04-14 10:30

import django.db.models.deletion
from django.db import migrations, models


def backfill_roaz_type(apps, schema_editor):
    RegionalConfiguration = apps.get_model('contracts', 'RegionalConfiguration')
    RegionalConfiguration.objects.filter(region_name__icontains='netwerk acute zorg').update(region_type='ROAZ')


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0032_rename_case_legacy_fields_to_care_native'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalconfiguration',
            name='region_type',
            field=models.CharField(
                choices=[
                    ('GEMEENTELIJK', 'Gemeentelijk'),
                    ('ROAZ', 'ROAZ'),
                    ('GGD', 'GGD'),
                    ('ZORGKANTOOR', 'Zorgkantoor'),
                ],
                db_index=True,
                default='GEMEENTELIJK',
                max_length=20,
                verbose_name='Regiotype',
            ),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='preferred_region',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='preferred_intakes',
                to='contracts.regionalconfiguration',
                verbose_name='Voorkeursregio',
            ),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='preferred_region_type',
            field=models.CharField(
                choices=[
                    ('GEMEENTELIJK', 'Gemeentelijk'),
                    ('ROAZ', 'ROAZ'),
                    ('GGD', 'GGD'),
                    ('ZORGKANTOOR', 'Zorgkantoor'),
                ],
                default='GEMEENTELIJK',
                max_length=20,
                verbose_name='Voorkeur regiotype',
            ),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='served_regions',
            field=models.ManyToManyField(
                blank=True,
                related_name='provider_profiles',
                to='contracts.regionalconfiguration',
                verbose_name="Bediende regio's",
            ),
        ),
        migrations.RunPython(backfill_roaz_type, migrations.RunPython.noop),
    ]
